feat(tasks): VolSync & Crunchy restore, others I haven't committed my Taskfiles in so long I honestly don't remember what I mainly changed in them and just assume they all work lol

diff --git a/.taskfiles/k8s/Taskfile.dist.yaml b/.taskfiles/k8s/Taskfile.dist.yaml
--- a/.taskfiles/k8s/Taskfile.dist.yaml
+++ b/.taskfiles/k8s/Taskfile.dist.yaml
@@ -1,8 +1,9 @@
 ---
+# General Kubernetes admin tasks
 version: "3"
 
 vars:
-  C: '{{ .C | default "biohazard" }}'
+  # C: '{{ .C | default "admin@biohazard" }}'
   TIMENOW:
     sh: date +%Y%m%d-%H%M%S
 
@@ -11,7 +12,7 @@ tasks:
     aliases: [nsps]
     desc: While true loop labelling a given namespace with Pod Security labels, if external source creates namespace (e.g. Azure Arc's Helm apply with `--create-namespace`)
     vars:
-      NS: '{{ or .NS (fail "Missing `NS` environment variable!") }}'
+      NS: &ns-fail '{{ or .NS (fail "Missing `NS` environment variable!") }}'
       PS: '{{ or .PS (fail "Missing `PS` environment variable!") }}'
     cmds:
       - while true; do kubectl label namespaces {{.NS}} "pod-security.kubernetes.io/enforce={{.PS}}" >/dev/null 2>/dev/null || true; kubectl label namespaces {{.NS}} "pod-security.kubernetes.io/enforce-version=latest" >/dev/null 2>/dev/null || true; done
@@ -21,32 +22,42 @@ tasks:
     internal: true
     desc: Wait for a job's pod to change its status to pending
     vars:
-      NAME: '{{ or .NAME (fail "Missing `NAME` environment variable!") }}'
-      NS: '{{ .NS | default "default" }}'
+      NAME: &name-fail '{{ or .NAME (fail "Missing `NAME` environment variable!") }}'
+      NS: *ns-fail
     cmds:
       - until [[ $(kubectl -n "{{.NS}}" get pod "{{.NAME}}" -o jsonpath='{.items[*].status.phase}') == "Pending" ]]; do sleep 1; done
 
   wait-pod-running:
-    aliases: [waitp]
+    aliases: [waitr]
     internal: true
     desc: Wait for a job's pod to change its status to pending
     vars:
-      NAME: '{{ or .NAME (fail "Missing `NAME` environment variable!") }}'
-      NS: '{{ .NS | default "default" }}'
+      NAME: *name-fail
+      NS: *ns-fail
     cmds:
       - until [[ $(kubectl -n "{{.NS}}" get pod "{{.NAME}}" -o jsonpath='{.items[*].status.phase}') == "Running" ]]; do sleep 1; done
+
+  wait-pod-delete:
+    aliases: [waitd]
+    internal: true
+    desc: Wait for a job's pod to delete
+    vars:
+      NAME: *name-fail
+      NS: *ns-fail
+    cmds:
+      - until kubectl wait pod -n {{.NS}} {{.NAME}} --for delete --timeout=1m; do sleep 1; done
 
   wait-finish:
     internal: true
     desc: Wait for a job's pod to change its status to pending
     vars:
-      NAME: '{{ or .NAME (fail "Missing `NAME` environment variable!") }}'
-      NS: '{{ .NS | default "default" }}'
+      NAME: *name-fail
+      NS: *ns-fail
       TYPE: '{{ .TYPE | default "job" }}'
       # WAIT_ARGS: '{{.WAIT_ARGS | default "echo \"{{.NAME}} is still running, logs:\" && kubectl -n {{.NS}} logs {{.NAME}} --since 2s -f;"}}'
     cmds:
       - |-
-        until kubectl -n {{.NS}} wait {{.TYPE}}/{{.NAME}} --for condition=complete --timeout=2s; do 
+        until kubectl -n {{.NS}} wait {{.TYPE}}/{{.NAME}} --for condition=complete --timeout=2s; do
           echo "{{.NAME}} is still running, logs:" && kubectl -n {{.NS}} logs {{.TYPE}}/{{.NAME}} --since 2s -f || true;
         done
 
@@ -68,13 +79,33 @@ tasks:
       SECRETS_FILE: "{{.ROOT_DIR}}/kube/clusters/{{.C}}/config/secrets.sops.env"
       VARS_FILE: "{{.ROOT_DIR}}/kube/clusters/{{.C}}/config/vars.sops.env"
       FCMD: '{{ .FCMD | default "cat" }}'
+      C: '{{.C | default "admin@biohazard"}}'
     cmds:
+      #- sops exec-env {{.SECRETS_FILE}} "sops exec-env {{.VARS_FILE}} \"{{.FCMD}} {{.F}} | envsubst | kubectl apply --context {{.C}} -f -\""
       - sops exec-env {{.SECRETS_FILE}} "sops exec-env {{.VARS_FILE}} \"{{.FCMD}} {{.F}} | envsubst | kubectl apply -f -\""
+
+  cilium-bootstrap-apply:
+    aliases: [cilium]
+    desc: Bootstrap Cilium onto new cluster, ready for Flux to take over managing Cilium.
+    # dir: "/{{.ROOT_DIR}}/kube/clusters/{{.C}}/talos"
+    vars:
+      C: '{{ or .C (fail "Missing C environment variable for cluster!") }}'
+    cmds:
+      - kubectl delete configmap -n kube-system cilium-config || true
+      - kubectl delete daemonset -n kube-system cilium || true
+      - kubectl delete deployment -n kube-system cilium-operator || true
+      - cp /{{.ROOT_DIR}}/kube/deploy/core/_networking/cilium/clusters/{{.C}}/helm-values.yaml /{{.ROOT_DIR}}/kube/deploy/core/_networking/cilium/app/bootstrap-install/base-values.yaml
+      - task: sops-apply
+        vars:
+          C: '{{.C | default "admin@biohazard"}}'
+          F: "/{{.ROOT_DIR}}/kube/deploy/core/_networking/cilium/app/bootstrap-install"
+          FCMD: "kustomize build --enable-helm"
+      - defer: rm -rf /{{.ROOT_DIR}}/kube/deploy/core/_networking/cilium/app/bootstrap-install/base-values.yaml
 
   newapp:
     desc: Copy app folder structure template, substitute APPNAME, and (TODO) prompt user for variables values such as DNS, UID etc.
     vars:
-      app: '{{ or .app (fail "Missing `app` variable!") }}'
+      APP: &app-fail '{{ or .APP (fail "Missing `app` variable!") }}'
     cmds:
       - cp -r ./kube/templates/test ./kube/deploy/apps/{{.app}}
       # lowercase, used for resource names etc
@@ -123,15 +154,75 @@ tasks:
         export KBENCH=$(curl -sL https://raw.githubusercontent.com/yasker/kbench/main/deploy/fio.yaml)
         [[ ! -z "{{.SC}}" ]] && export KBENCH=$(printf '%s\n' "${KBENCH}" | yq '. | select(.kind == "PersistentVolumeClaim").spec.storageClassName = "{{.SC}}"')
         [[ ! -z "{{.NODE}}" ]] && export KBENCH=$(printf '%s\n' "${KBENCH}" | yq '. | select(.kind == "Job").spec.template.spec.nodeSelector."kubernetes.io/hostname" = "{{.NODE}}"')
+        export KBENCH=$(printf '%s\n' "${KBENCH}" | yq '. | select(.kind == "PersistentVolumeClaim").metadata.name = "kbench-{{- .TIMENOW -}}"')
+        export KBENCH=$(printf '%s\n' "${KBENCH}" | yq '. | select(.kind == "Job").metadata.name = "kbench-{{- .TIMENOW -}}"')
+        export KBENCH=$(printf '%s\n' "${KBENCH}" | yq '. | (select(.kind == "Job").spec.template.spec.volumes.[] | select(.name == "vol").persistentVolumeClaim.claimName) |= "kbench-{{- .TIMENOW -}}"')
         printf '%s\n' "${KBENCH}" | kubectl delete -n {{.NS}} -f - || true
       - |-
         export KBENCH=$(curl -sL https://raw.githubusercontent.com/yasker/kbench/main/deploy/fio.yaml)
         [[ ! -z "{{.SC}}" ]] && export KBENCH=$(printf '%s\n' "${KBENCH}" | yq '. | select(.kind == "PersistentVolumeClaim").spec.storageClassName = "{{.SC}}"')
         [[ ! -z "{{.NODE}}" ]] && export KBENCH=$(printf '%s\n' "${KBENCH}" | yq '. | select(.kind == "Job").spec.template.spec.nodeSelector."kubernetes.io/hostname" = "{{.NODE}}"')
+        export KBENCH=$(printf '%s\n' "${KBENCH}" | yq '. | select(.kind == "PersistentVolumeClaim").metadata.name = "kbench-{{- .TIMENOW -}}"')
+        export KBENCH=$(printf '%s\n' "${KBENCH}" | yq '. | select(.kind == "Job").metadata.name = "kbench-{{- .TIMENOW -}}"')
+        export KBENCH=$(printf '%s\n' "${KBENCH}" | yq '. | (select(.kind == "Job").spec.template.spec.volumes.[] | select(.name == "vol").persistentVolumeClaim.claimName) |= "kbench-{{- .TIMENOW -}}"')
         printf '%s\n' "${KBENCH}" | kubectl apply -n {{.NS}} -f -
       - defer: *kbench-delete
       - task: wait-finish
         vars:
           NS: '{{ .NS | default "default" }}'
-          NAME: "kbench"
+          NAME: "kbench-{{- .TIMENOW -}}"
           TYPE: "job"
+
+  scale-to-0:
+    aliases: ["0"]
+    desc: Scale given workloads to 0
+    vars: &scale-vars
+      KS:
+        sh: |-
+          [[ -z "{{.KS}}" ]] && echo "{{.APP}}-app" || echo "{{.KS}}"
+      KSNS: '{{ .KSNS | default "flux-system" }}'
+      HR: '{{ .HR | default .APP }}'
+      HRNS:
+        sh: |-
+          [[ -n "{{.HRNS}}" ]] && echo "{{.HRNS}}" && exit || [[ -n "{{.NS}}" ]] && echo "{{.NS}}" && exit || echo "{{.APP}}"
+      APP: *app-fail
+      NS: '{{ .NS | default .APP }}'
+      REASON: '{{ .REASON | default .TIMENOW }}'
+    cmds:
+      - |- # annotate Flux Kustomization
+        [[ {{.KS}} != "false" ]] && kubectl annotate --overwrite kustomizations.kustomize.toolkit.fluxcd.io -n {{.KSNS}} {{.KS}} scaledown.home.arpa/reason={{.REASON}} || true
+      - |- # suspend Flux Kustomization
+        [[ {{.KS}} != "false" ]] && flux suspend kustomization -n {{.KSNS}} {{.KS}} || true
+      - |- # annotate Flux HelmRelease
+        [[ {{.HR}} != "false" ]] && kubectl annotate --overwrite helmreleases.helm.toolkit.fluxcd.io -n {{.HRNS}} {{.HR}} scaledown.home.arpa/reason={{.REASON}} || true
+      - |- # suspend Flux HelmRelease
+        [[ {{.HR}} != "false" ]] && flux suspend helmrelease -n {{.HRNS}} {{.HR}} || true
+      - |- # annotate Kubernetes controller with reason
+        kubectl annotate --overwrite deployment -n {{.NS}} {{.APP}} scaledown.home.arpa/reason={{.REASON}} || kubectl annotate --overwrite statefulset -n {{.NS}} {{.APP}} scaledown.home.arpa/reason={{.REASON}}
+      - |- # annotate Kubernetes controller with old replica count
+        kubectl annotate --overwrite deployment -n {{.NS}} {{.APP}} scaledown.home.arpa/replicas=$(kubectl get deployment -n {{.NS}} {{.APP}} -o jsonpath='{.spec.replicas}') || kubectl annotate --overwrite statefulset -n {{.NS}} {{.APP}} scaledown.home.arpa/replicas=$(kubectl get statefulset -n {{.NS}} {{.APP}} -o jsonpath='{.spec.replicas}')
+      - |- # scale down Kubernetes controller
+        kubectl scale deployment -n {{.NS}} {{.APP}} --replicas 0 || kubectl scale statefulset -n {{.NS}} {{.APP}} --replicas 0
+      - task: wait-pod-delete
+        vars:
+          NAME: '{{.APP}}'
+          NS: '{{.NS}}'
+
+  scale-back-up:
+    aliases: ["up"]
+    vars: *scale-vars
+    cmds:
+      - |- # scale up Kubernetes controller back to old replica count
+        kubectl scale deployment -n {{.NS}} {{.APP}} --replicas "$(kubectl get deployment -n {{.NS}} {{.APP}} -o jsonpath='{.metadata.annotations.scaledown\.home\.arpa/replicas}')" || kubectl scale statefulset -n {{.NS}} {{.APP}} --replicas "$(kubectl get statefulset -n {{.NS}} {{.APP}} -o jsonpath='{.metadata.annotations.scaledown\.home\.arpa/replicas}')"
+      - |- # remove old replica count annotation from Kubernetes controller
+        kubectl annotate deployment -n {{.NS}} {{.APP}} scaledown.home.arpa/replicas- || kubectl annotate statefulset -n {{.NS}} {{.APP}} scaledown.home.arpa/replicas-
+      - |- # remove reason annotation from Kubernetes controller
+        kubectl annotate deployment -n {{.NS}} {{.APP}} scaledown.home.arpa/reason- || kubectl annotate statefulset -n {{.NS}} {{.APP}} scaledown.home.arpa/reason-
+      - |- # resume Flux HelmRelease
+        [[ {{.HR}} != "disabled" ]] && flux resume helmrelease -n {{.HRNS}} {{.HR}} || true
+      - |- # remove reason annotation from Flux HelmRelease
+        [[ {{.HR}} != "disabled" ]] && kubectl annotate helmreleases.helm.toolkit.fluxcd.io -n {{.HRNS}} {{.HR}} scaledown.home.arpa/reason- || true
+      - |- # resume Flux Kustomization
+        [[ {{.KS}} != "disabled" ]] && flux resume kustomization -n {{.KSNS}} {{.KS}} || true
+      - |- # remove reason annotation from Flux Kustomization
+        [[ {{.KS}} != "disabled" ]] && kubectl annotate kustomizations.kustomize.toolkit.fluxcd.io -n {{.KSNS}} {{.KS}} scaledown.home.arpa/reason- || true
diff --git a/.taskfiles/rook/Taskfile.dist.yaml b/.taskfiles/rook/Taskfile.dist.yaml
--- a/.taskfiles/rook/Taskfile.dist.yaml
+++ b/.taskfiles/rook/Taskfile.dist.yaml
@@ -71,10 +71,10 @@ tasks:
     cmds:
       # TODO: mimic deviceFilter
       - envsubst < <(cat {{.JOB_TEMPLATE}}) | kubectl apply -f -
-      - |- 
+      - |-
         kubectl -n kube-system logs job/{{.JOB_NAME}} -f || true;
-        until kubectl -n kube-system wait job/{{.JOB_NAME}} --for condition=complete --timeout=2s; do 
-          echo "Job {{.JOB_NAME}} is still running, logs:" && 
+        until kubectl -n kube-system wait job/{{.JOB_NAME}} --for condition=complete --timeout=2s; do
+          echo "Job {{.JOB_NAME}} is still running, logs:" &&
           kubectl -n kube-system logs job/{{.JOB_NAME}} -f || true;
         done;
       # - kubectl -n kube-system logs job/{{.JOB_NAME}}
@@ -122,6 +122,19 @@ tasks:
         vars:
           NODE: '{{.NODE}}'
 
+  wipe-nodes-biohazard:
+    desc: Wipe all nodes in cluster "nuclear"
+    dir: '/{{.ROOT_DIR}}/.taskfiles/rook'
+    cmds:
+      - task: wipe-node
+        vars:
+          NODE: "ange"
+          CEPH_DISK: "/dev/disk/by-id/ata-INTEL_SSDSC2BB016T4_BTWD709202L91P6HGN"
+      - task: wipe-node
+        vars:
+          NODE: "charlotte"
+          CEPH_DISK: "/dev/disk/by-id/ata-INTEL_SSDSC2BB016T4_BTWD709202JK1P6HGN" # I swear I'll forget to update this here when I have to change the disk
+
   wipe-nodes-nuclear:
     desc: Wipe all nodes in cluster "nuclear"
     dir: '/{{.ROOT_DIR}}/.taskfiles/rook'
@@ -134,6 +147,23 @@ tasks:
         vars:
           NODE: "humming"
           CEPH_DISK: "/dev/disk/by-id/ata-INTEL_SSDSC2BB016T4_BTWD709202L91P6HGN"
+
+  force-delete-cluster:
+    desc: |-
+      Sometimes Rook seems to fail applying the cluster and want to delete it before it even gets anything set up, this Task will force delete all finalizers to delete all unready Ceph resources.
+    dir: '/{{.ROOT_DIR}}/.taskfiles/rook'
+    vars:
+      C: '{{ or .C (fail "Missing `C` environment variable for cluster!") }}'
+    cmds:
+      - helm uninstall -n rook-ceph rook-ceph-cluster-{{.C}} && true || true
+      - |-
+        for CRD in $(kubectl get crd -n rook-ceph | awk '/ceph.rook.io/ {print $1}'); do
+            kubectl get -n rook-ceph "$CRD" -o name | \
+            xargs -I {} kubectl patch -n rook-ceph {} --type merge -p '{"metadata":{"finalizers": []}}' && true || true
+        done
+      - |-
+        kubectl -n rook-ceph patch configmap rook-ceph-mon-endpoints --type merge -p '{"metadata":{"finalizers": []}}' && true || true
+        kubectl -n rook-ceph patch secrets rook-ceph-mon --type merge -p '{"metadata":{"finalizers": []}}' && true || true
 
   reinstall:
     desc: |-
@@ -149,23 +179,17 @@ tasks:
           C: '{{.C}}'
       - flux suspend ks 0-{{.C}}-config
       - flux suspend ks 1-core-storage-rook-ceph-app
-      - flux suspend ks 1-core-storage-rook-ceph-cluster
-      - helm uninstall -n rook-ceph rook-ceph-cluster && true || true
-      - flux delete hr -n rook-ceph rook-ceph-cluster --silent && true || true
-      - |-
-        for CRD in $(kubectl get crd -n rook-ceph | awk '/ceph.rook.io/ {print $1}'); do
-            kubectl get -n rook-ceph "$CRD" -o name | \
-            xargs -I {} kubectl patch -n rook-ceph {} --type merge -p '{"metadata":{"finalizers": []}}' && true || true
-        done
-      - |-
-        kubectl -n rook-ceph patch configmap rook-ceph-mon-endpoints --type merge -p '{"metadata":{"finalizers": []}}' && true || true
-        kubectl -n rook-ceph patch secrets rook-ceph-mon --type merge -p '{"metadata":{"finalizers": []}}' && true || true
+      - flux suspend ks 1-core-storage-rook-ceph-cluster-{{.C}}
+      - task: force-delete-cluster
+        vars:
+          C: '{{.C}}'
+      # - flux delete hr -n rook-ceph rook-ceph-cluster-{{.C}} --silent && true || true
       - helm uninstall -n rook-ceph rook-ceph && true || true
-      - flux delete hr -n rook-ceph rook-ceph --silent && true || true
+      # - flux delete hr -n rook-ceph rook-ceph --silent && true || true
       - kubectl get namespaces rook-ceph && until kubectl delete namespaces rook-ceph; do kubectl get namespaces rook-ceph -o jsonpath="{.status}"; done || true
       - task: wipe-nodes-{{.C}}
       # - task: wipe-nodes-{{.C}} # run again in case wipe fails
       - flux suspend ks 0-{{.C}}-config && flux resume ks 0-{{.C}}-config
       - flux suspend ks 1-core-storage-rook-ceph-app && flux resume ks 1-core-storage-rook-ceph-app
-      - flux suspend ks 1-core-storage-rook-ceph-cluster && flux resume ks 1-core-storage-rook-ceph-cluster
+      - flux suspend ks 1-core-storage-rook-ceph-cluster-{{.C}} && flux resume ks 1-core-storage-rook-ceph-cluster-{{.C}}
       # - task: osd-prepare-logs # uncomment to debug OSD prepare errors with while true loop, since the job re-runs 6 times and overwrites the previous runs' logs
