feat: add useful Rook debug tasks, k8s iperf2 pods

diff --git a/.taskfiles/k8s/Taskfile.dist.yaml b/.taskfiles/k8s/Taskfile.dist.yaml
--- a/.taskfiles/k8s/Taskfile.dist.yaml
+++ b/.taskfiles/k8s/Taskfile.dist.yaml
@@ -3,17 +3,43 @@ version: "3"
 
 vars:
   C: '{{ .C | default "biohazard" }}'
+  TIMENOW:
+    sh: date +%Y%m%d-%H%M%S
 
 tasks:
-  wait-job-pending:
-    aliases: [waitjob]
+  wait-pod-pending:
+    aliases: [waitp]
     internal: true
     desc: Wait for a job's pod to change its status to pending
     vars:
-      NAMESPACE: '{{ or .NAMESPACE (fail "Missing `NAMESPACE` environment variable!") }}'
-      JOB_NAME: '{{ or .JOB_NAME (fail "Missing `JOB_NAME` environment variable!") }}'
+      NAME: '{{ or .NAME (fail "Missing `NAME` environment variable!") }}'
+      NS: '{{ .NS | default "default" }}'
     cmds:
-      - until [[ $(kubectl -n "${NAMESPACE}" get pod -l job-name="${JOB_NAME}" -o jsonpath='{.items[*].status.phase}') == "Pending" ]]; do sleep 1; done
+      - until [[ $(kubectl -n "{{.NS}}" get pod "{{.NAME}}" -o jsonpath='{.items[*].status.phase}') == "Pending" ]]; do sleep 1; done
+
+  wait-pod-running:
+    aliases: [waitp]
+    internal: true
+    desc: Wait for a job's pod to change its status to pending
+    vars:
+      NAME: '{{ or .NAME (fail "Missing `NAME` environment variable!") }}'
+      NS: '{{ .NS | default "default" }}'
+    cmds:
+      - until [[ $(kubectl -n "{{.NS}}" get pod "{{.NAME}}" -o jsonpath='{.items[*].status.phase}') == "Running" ]]; do sleep 1; done
+
+  wait-finish:
+    internal: true
+    desc: Wait for a job's pod to change its status to pending
+    vars:
+      NAME: '{{ or .NAME (fail "Missing `NAME` environment variable!") }}'
+      NS: '{{ .NS | default "default" }}'
+      # TYPE: '{{ .TYPE | default "job" }}'
+      # WAIT_ARGS: '{{.WAIT_ARGS | default "echo \"{{.NAME}} is still running, logs:\" && kubectl -n {{.NS}} logs {{.NAME}} --since 2s -f;"}}'
+    cmds:
+      - |-
+        until kubectl -n {{.NS}} wait {{.NAME}} --for condition=complete --timeout=2s; do 
+          echo "{{.NAME}} is still running, logs:" && kubectl -n {{.NS}} logs {{.NAME}} --since 2s -f || true;
+        done
 
   get-public-ingresses:
     aliases: [gpi]
@@ -46,3 +72,32 @@ tasks:
       - grep -lR 'APPNAME' ./kube/3-deploy/2-apps/{{.app}}/ | xargs -I% sed -i 's/${APPNAME}/{{.app}}/g' %
       # uppercase, for variable substitution references e.g. ${APP_DNS_AUTHENTIK}
       - grep -lR 'APPNAME' ./kube/3-deploy/2-apps/{{.app}}/ | xargs -I% sed -i 's/_APPNAME}/_{{.app}}}/g;s/\(_{{.app}}}\)/\U\1/g' %
+
+  iperf2:
+    desc: Start a iperf2 server on one node, and iperf2 client on another node, to benchmark network performance.
+    dir: "/{{.ROOT_DIR}}/.taskfiles/k8s/template/iperf2"
+    vars: &iperf2-vars
+      SERVER_NAME: &iperf2-server-name 'iperf2-server-{{- .TIMENOW -}}'
+      SERVER_NS: &iperf2-server-ns '{{ .SERVER_NS | default "default" }}'
+      CLIENT_NAME: &iperf2-client-name 'iperf2-client-{{- .TIMENOW -}}'
+      CLIENT_NS: &iperf2-client-ns '{{ .CLIENT_NS | default "default" }}'
+      CLUSTER_DOMAIN: '{{ .CLUSTER_DOMAIN | default "cluster.local" }}'
+      SERVER_PORT: '{{ .SERVER_PORT | default "5001" }}'
+      SERVER_NODE: '{{ or .SERVER_NODE (fail "Missing `SERVER_NODE` environment variable!") }}'
+      CLIENT_NODE: '{{ or .CLIENT_NODE (fail "Missing `CLIENT_NODE` environment variable!") }}'
+      SERVER_ARGS: '{{ .SERVER_ARGS | default "" }}'
+      CLIENT_ARGS: '{{ .CLIENT_ARGS | default "" }}'
+    env: *iperf2-vars
+    cmds:
+      - cat ./server.yaml | envsubst | kubectl apply -f -
+      - defer: cat ./server.yaml | envsubst | kubectl delete -f -
+      - task: wait-pod-running
+        vars:
+          NAME: '-l job-name={{.SERVER_NAME}}'
+          NS: '{{.SERVER_NS}}'
+      - cat ./client.yaml | envsubst | kubectl apply -f -
+      - defer: cat ./client.yaml | envsubst | kubectl delete -f -
+      - task: wait-finish
+        vars:
+          NAME: 'jobs/{{.CLIENT_NAME}}'
+          NS: '{{.CLIENT_NS}}'
diff --git a/.taskfiles/rook/Taskfile.dist.yaml b/.taskfiles/rook/Taskfile.dist.yaml
--- a/.taskfiles/rook/Taskfile.dist.yaml
+++ b/.taskfiles/rook/Taskfile.dist.yaml
@@ -17,24 +17,51 @@ includes:
   cluster:
     internal: true
     taskfile: ../cluster
+  talos:
+    internal: true
+    taskfile: ../talos
 
 tasks:
+  osd-prepare-logs:
+    aliases: [osdlogs]
+    desc: Stream all logs for the `osd-prepare` Job.
+    cmds:
+      - while true; do kubectl logs -n rook-ceph -l app=rook-ceph-osd-prepare -c provision --tail 999999999999999999 -f 2>&1 | grep -v "No resources found" | tee --append /tmp/rook-ceph-osd-prepare-{{- .TIME -}}.log; done
+      # - |-
+      #   JOBDONE=no
+      #   until $JOBDONE == "yes"; do
+      #     kubectl logs -n rook-ceph jobs/rook-ceph-osd-prepare-blackfish --tail 999999999999999999 -f &
+      #     PID1=$!
+      #     kubectl wait -n rook-ceph job -l app=rook-ceph-osd-prepare --for condition=complete --timeout=1m && kill $PID1 && JOBDONE=yes
+      #   done
+      # - |-
+      #   kubectl logs -n rook-ceph -l app=rook-ceph-osd-prepare --tail 999999999999999999 -f;
+      #   until kubectl wait -n rook-ceph job -l app=rook-ceph-osd-prepare --for condition=complete --timeout=1m; do
+      #     kubectl logs -n rook-ceph -l app=rook-ceph-osd-prepare --tail 999999999999999999 -f | tee /tmp/rook-ceph-osd-prepare.log;
+      #   done
+
+  osd-prepare-copy-job-debug:
+    aliases: [osdjobcp]
+    desc: Copy OSD-prepare job YAML, remove unnecessary fields, change command ran for user to manually shell and run commands. Used for debugging OSD-prepare job with its env and configurations remaining.
+    silent: true
+    vars:
+      NODE: '{{ or .NODE (fail "`NODE` is required") }}'
+    cmds:
+      - |-
+        kubectl get jobs -n rook-ceph rook-ceph-osd-prepare-{{.NODE}} -o yaml | yq 'del(.status, .metadata.annotations, .metadata.creationTimestamp, .metadata.generation, .metadata.ownerReferences, .metadata.resourceVersion, .metadata.uid, .spec.selector, .spec.template.metadata.labels.controller-uid) | .metadata.name = "test-rook-ceph-osd-prepare-{{.NODE}}" | .spec.template.metadata.labels.job-name = "test-rook-ceph-osd-prepare-{{.NODE}}" | .spec.template.spec.containers.0.command = ["/bin/sh", "-c"] | .spec.template.spec.containers.0.args = ["sleep 999999999"]' | kubectl apply -f -
+
   zap-disk:
     desc: Prepare a disk to be used as a Ceph OSD on specified node by zapping all data and partition data.
-    internal: true
     dir: '/{{.ROOT_DIR}}/.taskfiles/rook'
     cmds:
       # TODO: mimic deviceFilter
       - envsubst < <(cat {{.JOB_TEMPLATE}}) | kubectl apply -f -
-      # - task: k8s:wait-job-pending
-      #   vars:
-      #     JOB_NAME: '{{.wipeCephDiskJobName}}'
-      #     NAMESPACE: kube-system
       - |- 
-        until kubectl -n kube-system wait job/{{.JOB_NAME}} --for condition=complete --timeout=1m; do 
+        kubectl -n kube-system logs job/{{.JOB_NAME}} -f || true;
+        until kubectl -n kube-system wait job/{{.JOB_NAME}} --for condition=complete --timeout=2s; do 
           echo "Job {{.JOB_NAME}} is still running, logs:" && 
           kubectl -n kube-system logs job/{{.JOB_NAME}} -f;
-        done
+        done;
       # - kubectl -n kube-system logs job/{{.JOB_NAME}}
       - defer: kubectl -n kube-system delete job {{.JOB_NAME}}
     vars:
@@ -48,16 +75,10 @@ tasks:
 
   wipe-state:
     desc: Wipe all Ceph state on specified node.
-    internal: true
     dir: '/{{.ROOT_DIR}}/.taskfiles/rook'
     cmds:
       - envsubst < <(cat {{.JOB_TEMPLATE}}) | kubectl apply -f -
-      # - task: k8s:wait-job-pending
-      #   vars:
-      #     JOB_NAME: '{{.wipeCephDiskJobName}}'
-      #     NAMESPACE: kube-system
-      - until kubectl -n kube-system wait job/{{.JOB_NAME}} --for condition=complete --timeout=1m; do echo "Job {{.JOB_NAME}} is still running, logs:" && kubectl -n kube-system logs job/{{.JOB_NAME}} -f; done
-      # - kubectl -n kube-system logs job/{{.JOB_NAME}}
+      - until kubectl -n kube-system wait job/{{.JOB_NAME}} --for condition=complete --timeout=2s; do echo "Job {{.JOB_NAME}} is still running, logs:" && kubectl -n kube-system logs job/{{.JOB_NAME}} -f; done
       - defer: kubectl -n kube-system delete job {{.JOB_NAME}}
     vars:
       NODE: '{{ or .NODE (fail "`NODE` is required") }}'
@@ -82,6 +103,9 @@ tasks:
       - task: wipe-state
         vars:
           NODE: '{{.NODE}}'
+      - task: talos:reboot
+        vars:
+          NODE: '{{.NODE}}'
 
   wipe-nodes-nuclear:
     desc: Wipe all nodes in cluster "nuclear"
@@ -90,7 +114,11 @@ tasks:
       - task: wipe-node
         vars:
           NODE: "blackfish"
-          CEPH_DISK: "/dev/disk/by-id/ata-INTEL_SSDSC2BB016T4_BTWD709202JK1P6HGN"
+          CEPH_DISK: "/dev/disk/by-id/ata-INTEL_SSDSC2BB016T4_BTWD709202JK1P6HGN" # I swear I'll forget to update this here when I have to change the disk
+      - task: wipe-node
+        vars:
+          NODE: "humming"
+          CEPH_DISK: "/dev/disk/by-id/ata-INTEL_SSDSC2BB016T4_BTWD709202L91P6HGN"
 
   reinstall:
     desc: |-
@@ -121,6 +149,8 @@ tasks:
       - flux delete hr -n rook-ceph rook-ceph --silent && true || true
       - kubectl get namespaces rook-ceph && until kubectl delete namespaces rook-ceph; do kubectl get namespaces rook-ceph -o jsonpath="{.status}"; done || true
       - task: wipe-nodes-{{.C}}
+      - task: wipe-nodes-{{.C}} # run again in case wipe fails
       - flux suspend ks 0-{{.C}}-config && flux resume ks 0-{{.C}}-config
       - flux suspend ks 1-core-storage-rook-ceph-app && flux resume ks 1-core-storage-rook-ceph-app
       - flux suspend ks 1-core-storage-rook-ceph-cluster && flux resume ks 1-core-storage-rook-ceph-cluster
+      # - task: osd-prepare-logs # uncomment to debug OSD prepare errors with while true loop, since the job re-runs 6 times and overwrites the previous runs' logs
